- group: name=celery
- user: name=celery group=celery
- file: path=/home/celery state=directory owner=celery group=celery mode=774

- name: install libraries
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-dev
    - python-virtualenv
    - postgresql-client
    - libpq-dev
    - supervisor
    - node
    - npm

- name: Create frontend directory
  file: path=/www/frontend state=directory

- name: Create backend directory
  file: path=/www/backend state=directory

- name: Nginx config for app
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/frontend.conf
  notify: restart nginx

- name: Supervisor config for backend app
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/breta.conf
  notify: restart supervisor

- name: install npm dependencies
  npm: name=yuglify global=yes
